// astro/src/components/List/List.tsx
import React, { useCallback } from 'react'
import styles from './list.scss';

export default function List(props: { data: any, setCurrentParking: CallableFunction }) {

  const setDetail = useCallback((index: Number) => {
    props.setCurrentParking(index);
  }, [props])


  return (
    <aside>
      <ul className='list'>
        {Object.values(props.data).map((data: any, index: Number) => {
          return (
            <li onClick={() => setDetail(index)} key={data.recordid}>
              <div>{data.fields.name}</div>
              <div>{data.fields.availablecapacity} /  {data.fields.totalcapacity} vrij</div>
            </li>
          );
        })}
      </ul>
    </aside>
  )
}

// qwik/src/components/list/List.tsx
import { component$, $ } from '@builder.io/qwik';
import './list.scss'

export const List = component$((props: { data: any, setActive: CallableFunction }) => {

  // eslint-disable-next-line qwik/valid-lexical-scope
  const setDetail = $((index: Number) => props.setActive(index));

  return (
    <aside>
      <ul class={'list'}>
        {Object.values(props.data).map((data: any, index: Number) => {

          return (
            // eslint-disable-next-line qwik/valid-lexical-scope
            <li onClick$={() => setDetail(index)} key={data.recordid}>
              <div>{data.fields.name}</div>
              <div>{data.fields.availablecapacity} /  {data.fields.totalcapacity} vrij</div>
            </li>
          );
        })}
      </ul>
    </aside>
  )
});
