// sveltekit/src/components/Detail/Detail.svelte
<script lang="ts">
  import GoogleMap from '../GoogleMap/GoogleMap.svelte';
  import ModalBox from '../ModalBox/ModalBox.svelte';
  import './detail.scss';
  export let data: any;
  export let nextParking: any;
  export let previousParking: any;
  export let refreshData: any;
  export let modalState: boolean = false;
</script>

<section class="detail">
  <header>
    <h2>{data.fields.name}</h2>
    <div class="buttons">
      <button on:click={previousParking}><i class="fas fa-arrow-alt-circle-left"></i></button>
      <button on:click={nextParking}><i class="fas fa-arrow-alt-circle-right"></i></button>
      <button on:click={() => modalState = true}><i class="fas fa-info-circle"></i></button>
    </div>
    <div class="details">
      <span>laatst geupdate: {new Date(data.fields.lastupdate).toLocaleTimeString()}</span>
      <button on:click={refreshData}><i class="fas fa-arrows-rotate"></i></button>
    </div>
  </header>
  
  <!-- <GoogleMap
    bind:name = {data.fields.name}
    /> -->

    <ModalBox
      title={data.fields.name}
      data={data}
      nextParking={nextParking}
      previousParking={previousParking}
      bind:modalState
    />
</section>

// astro/src/components/Detail/Detail.tsx
import React, { useState } from 'react'
import GoogleMap from '../GoogleMap/GoogleMap';
import ModalBox from '../ModalBox/ModalBox';
import './detail.scss';

export default function Detail(props: { data: any, nextParking: CallableFunction, previousParking: CallableFunction, refresh: CallableFunction }) {

  const [modalActive, setModalActive] = useState(false);

  return (
    <section className='detail'>
      {(props.data) &&
        <>
          <header>
            <h2>{props.data.fields.name}</h2>
            <div className='buttons'>
              <button onClick={() => props.previousParking()}><i className="fas fa-arrow-alt-circle-left"></i></button>
              <button onClick={() => props.nextParking()}><i className="fas fa-arrow-alt-circle-right"></i></button>
              <button onClick={() => setModalActive(true)}><i className="fas fa-info-circle"></i></button>            </div>
            <div className='details'>
              <span>laatst geupdate: {new Date(props.data.fields.lastupdate).toLocaleTimeString()}</span>
              <button onClick={() => props.refresh()}><i className="fas fa-arrows-rotate"></i></button>
            </div>
          </header>

          <GoogleMap name={props.data.fields.name} />

          <ModalBox
            title={`Details ${props.data.fields.name}`}
            modalState={modalActive}
            updateModalState={setModalActive}
            content={
              <div className='modalContent'>
                <header>
                  {props.data.fields.availablecapacity} / {props.data.fields.totalcapacity} vrij
                  Open: {props.data.fields.isopennow === 0 ? "nee" : "ja"}
                  <div className='modalButtons'>
                    <button onClick={() => props.previousParking()}><i className="fas fa-arrow-alt-circle-left"></i></button>
                    <button onClick={() => props.nextParking()}><i className="fas fa-arrow-alt-circle-right"></i></button>
                  </div>
                </header>
                <p>{props.data.fields.description}</p>
                <ul>
                  <li>Gratis: {props.data.fields.freeparking === 0 ? "nee" : "ja"}</li>
                  <li>Openings uren: {props.data.fields.openingtimesdescription}</li>
                  <li>Type: {props.data.fields.type === "offStreetParkingGround" ? "parkeerplaats buiten de straat" : "parkeerplaats"}</li>
                </ul>
              </div>
            }
          />
        </>
      }
      {
        (!props.data) &&
        <span>
          no data selected
        </span>
      }
    </section >
  )
}
