// qwik/src/routes/index.tsx
import { Resource, component$, useResource$, useSignal, $ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { About } from '~/components/about/About';
import { Detail } from '~/components/detail/Detail';
import { List } from '~/components/list/List';
import Navbar from '~/components/navbar/Navbar';

export default component$(() => {

  const active = useSignal<number>(0);

  const fetchData = useResource$<[]>(({ track, cleanup }) => {
    const controller = new AbortController();
    track(() => controller);
    cleanup(() => controller.abort());
    return getData(controller);
  })

  const setActive = $((index: number) => {
    active.value = index;
  });

  return (
    <>
      <Navbar />

      <main>
        <About />

        <Resource
          value={fetchData}
          onPending={() => <div>Loading...</div>}
          onRejected={(error) => <div>{error.toString()}</div>}
          onResolved={(data: []) => {
            return <>
              <List
                data={data}
                setActive={setActive}
              />
              <Detail
                data={data[active.value]}
                nextParking={$(() => {
                  if (active.value < data.length - 1) {
                    active.value++;
                  } else {
                    active.value = 0;
                  }
                })}
                previousParking={$(() => {
                  if (active.value > 0) {
                    active.value--;
                  } else {
                    active.value = data.length - 1;
                  }
                })}
              />
            </>;
          }
          }
        />
      </main>
    </>
  );
});

export const head: DocumentHead = {
  title: 'Welcome to Qwik',
  meta: [
    {
      name: 'description',
      content: 'Qwik site description',
    },
  ],
};

export async function getData(controller?: AbortController): Promise<[]> {
  const res = await fetch('https://data.stad.gent/api/records/1.0/search/?dataset=bezetting-parkeergarages-real-time', {
    signal: controller?.signal,
  });
  const json = await res.json();
  return json.records;
}

// sveltekit/src/routes/+page.svelte
<script >
// @ts-nocheck

	import Detail from '../components/Detail/Detail.svelte';
	import List from '../components/List/List.svelte';
	import Navbar from '../components/Navbar/Navbar.svelte';
  import Welcome from '../components/Welcome/Welcome.svelte';
	import './styles.scss';

	export let data;
	let currentParking = 0;

	 async function refreshData ()  {
    const res = await fetch('https://data.stad.gent/api/records/1.0/search/?dataset=bezetting-parkeergarages-real-time');
    const newData = await res.json();
		data.props = {data: newData}
  };

	function nextParking () {
		if (currentParking >= data.props.data.records.length - 1) {
			currentParking = 0;
      return;
    }
    currentParking ++;
	}

	function previousParking() {
		if (currentParking <= 0) {
			currentParking = data.props.data.records.length - 1;
			return;
		}
		currentParking --;
	}

</script>

<svelte:head>
	<title>Home</title>
	<meta name="description" content="Svelte demo app" />
</svelte:head>

<Navbar/>

<main>
	<Welcome/>

	<List 
		data={data.props.data.records}
		bind:currentParking
	/>

	<Detail 
		data={data.props.data.records[currentParking]}
		previousParking={previousParking}
		nextParking={nextParking}
		refreshData={refreshData}
	/>
</main>
