// sveltekit/src/components/List/List.svelte
<script lang="ts">
  import './list.scss';
  export let data: any;
  export let currentParking: number;

  const setParking = (index: number) => {
    currentParking = index;
  };

</script>

<aside>
  <ul class="list">
    <!-- Loop over the data -->
    {#each data as item}
      <!-- svelte-ignore a11y-click-events-have-key-events -->
      <li on:click={() => setParking(data.indexOf(item))}>
        <div>{item.fields.name}</div>
        <div>{item.fields.availablecapacity} / {item.fields.totalcapacity}</div>
      </li>
    {/each}
  </ul>
</aside>

// astro/src/components/List/List.tsx
import React, { useCallback } from 'react'
import styles from './list.scss';

export default function List(props: { data: any, setCurrentParking: CallableFunction }) {

  const setDetail = useCallback((index: Number) => {
    props.setCurrentParking(index);
  }, [props])


  return (
    <aside>
      <ul className='list'>
        {Object.values(props.data).map((data: any, index: Number) => {
          return (
            <li onClick={() => setDetail(index)} key={data.recordid}>
              <div>{data.fields.name}</div>
              <div>{data.fields.availablecapacity} /  {data.fields.totalcapacity} vrij</div>
            </li>
          );
        })}
      </ul>
    </aside>
  )
}
